user nobody;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 768;
    # !!! ЗДЕСЬ ОШИБКА !!! 
    # Студент: убери лишнюю точку с запятой в следующей строке
    use epoll;;
}

http {
    sendfile on;
    tcp_nopush on;
    
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    
    keepalive_timeout 65;
    
    server {
        listen 80;
        server_name localhost;
        
        root /var/www/html;
        index index.html;
        
        location / {
            try_files $uri $uri/ =404;
        }
    }
}