name: Run Test Container

on:
  push:
    branches: [main]
  workflow_dispatch:  # позволяет запускать вручную из интерфейса GitHub

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t test-container ./Tests/
      
      - name: Run container
        run: docker run test-container
