name: SSH Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Create network
        run: docker network create test-net
      
      - name: Run SSH server
        run: |
          docker build -t server ./exams/exam3
          docker run -d --name server --network test-net server
          sleep 5
      
      - name: Run client and connect
        run: |
          # Используем готовый образ alpine и устанавливаем sshpass на лету
          docker run --rm --network test-net alpine:latest \
            sh -c "apk add --no-cache openssh-client sshpass && sshpass -p 'exam2026' ssh -o StrictHostKeyChecking=no student@server 'echo Connected'"
      
      - name: Cleanup
        if: always()
        run: |
          docker stop server || true
          docker rm server || true
          docker network rm test-net || true
